/**
 * A curated list of popular Google Fonts for the picker's autocomplete.
 * This is NOT exhaustive — the picker accepts ANY typed family name, so fonts
 * not listed here still work; this just powers the searchable dropdown.
 */
export const GOOGLE_FONTS: string[] = [
  'ABeeZee', 'Abel', 'Abril Fatface', 'Aclonica', 'Acme', 'Alata', 'Albert Sans', 'Alegreya',
  'Alegreya Sans', 'Alfa Slab One', 'Alice', 'Almarai', 'Amatic SC', 'Amiri', 'Anek Latin',
  'Anton', 'Antonio', 'Archivo', 'Archivo Black', 'Archivo Narrow', 'Arimo', 'Arsenal',
  'Arvo', 'Asap', 'Asap Condensed', 'Assistant', 'Atkinson Hyperlegible', 'Azeret Mono',
  'B612', 'B612 Mono', 'Bai Jamjuree', 'Barlow', 'Barlow Condensed', 'Barlow Semi Condensed',
  'Be Vietnam Pro', 'Bebas Neue', 'Bitter', 'Bodoni Moda', 'Bree Serif', 'Bricolage Grotesque',
  'Cabin', 'Cabin Condensed', 'Cairo', 'Caprasimo', 'Cardo', 'Carlito', 'Carme', 'Catamaran',
  'Caveat', 'Chakra Petch', 'Changa', 'Chivo', 'Cinzel', 'Comfortaa', 'Commissioner',
  'Concert One', 'Cookie', 'Cormorant', 'Cormorant Garamond', 'Courgette', 'Courier Prime',
  'Crimson Pro', 'Crimson Text', 'Cuprum', 'DM Mono', 'DM Sans', 'DM Serif Display',
  'DM Serif Text', 'Dancing Script', 'Darker Grotesque', 'Dela Gothic One', 'Domine', 'Dosis',
  'EB Garamond', 'Eczar', 'El Messiri', 'Electrolize', 'Encode Sans', 'Epilogue', 'Exo',
  'Exo 2', 'Faustina', 'Figtree', 'Finlandica', 'Fira Code', 'Fira Mono', 'Fira Sans',
  'Fira Sans Condensed', 'Fjalla One', 'Frank Ruhl Libre', 'Fraunces', 'Fredoka', 'Gabarito',
  'Gelasio', 'Geologica', 'Geist', 'Gentium Book Plus', 'Gloock', 'Golos Text', 'Gothic A1',
  'Gowun Batang', 'Gowun Dodum', 'Great Vibes', 'Grenze Gotisch', 'Gruppo', 'Hahmlet',
  'Hanken Grotesk', 'Heebo', 'Hind', 'Hind Madurai', 'Hind Siliguri', 'IBM Plex Mono',
  'IBM Plex Sans', 'IBM Plex Sans Condensed', 'IBM Plex Serif', 'Inclusive Sans', 'Inconsolata',
  'Inder', 'Instrument Sans', 'Instrument Serif', 'Inter', 'Inter Tight', 'Jaldi', 'JetBrains Mono',
  'Josefin Sans', 'Josefin Slab', 'Jost', 'Kanit', 'Karla', 'Kalam', 'Kaushan Script', 'Khand',
  'Kreon', 'Kufam', 'Kumbh Sans', 'Lato', 'League Gothic', 'League Spartan', 'Lexend',
  'Lexend Deca', 'Libre Barcode 39', 'Libre Baskerville', 'Libre Caslon Text', 'Libre Franklin',
  'Lilita One', 'Literata', 'Lobster', 'Lobster Two', 'Lora', 'Luckiest Guy', 'Macondo',
  'Manrope', 'Marcellus', 'Markazi Text', 'Martel', 'Martian Mono', 'Maven Pro', 'Merienda',
  'Merriweather', 'Merriweather Sans', 'Michroma', 'Mitr', 'Montagu Slab', 'Montserrat',
  'Montserrat Alternates', 'Mukta', 'Mulish', 'Nanum Gothic', 'Nanum Myeongjo', 'Newsreader',
  'Noto Kufi Arabic', 'Noto Naskh Arabic', 'Noto Sans', 'Noto Sans Display', 'Noto Sans JP',
  'Noto Sans KR', 'Noto Sans Mono', 'Noto Sans SC', 'Noto Sans TC', 'Noto Serif',
  'Noto Serif Display', 'Noto Serif JP', 'Nunito', 'Nunito Sans', 'Old Standard TT', 'Onest',
  'Open Sans', 'Orbitron', 'Oswald', 'Outfit', 'Overpass', 'Overpass Mono', 'Oxanium',
  'Oxygen', 'PT Mono', 'PT Sans', 'PT Sans Narrow', 'PT Serif', 'Pacifico', 'Padauk',
  'Paytone One', 'Permanent Marker', 'Petrona', 'Philosopher', 'Piazzolla', 'Play', 'Playball',
  'Playfair Display', 'Playfair Display SC', 'Plus Jakarta Sans', 'Poppins', 'Prata',
  'Prompt', 'Public Sans', 'Quattrocento', 'Quattrocento Sans', 'Questrial', 'Quicksand',
  'Rajdhani', 'Raleway', 'Readex Pro', 'Recursive', 'Red Hat Display', 'Red Hat Mono',
  'Red Hat Text', 'Reddit Sans', 'Rethink Sans', 'Roboto', 'Roboto Condensed', 'Roboto Flex',
  'Roboto Mono', 'Roboto Serif', 'Roboto Slab', 'Rokkitt', 'Ropa Sans', 'Rowdies', 'Rubik',
  'Rubik Mono One', 'Ruda', 'Sacramento', 'Saira', 'Saira Condensed', 'Sansita', 'Sarabun',
  'Schibsted Grotesk', 'Sen', 'Shadows Into Light', 'Signika', 'Signika Negative', 'Silkscreen',
  'Sora', 'Source Code Pro', 'Source Sans 3', 'Source Serif 4', 'Space Grotesk', 'Space Mono',
  'Spectral', 'Spline Sans', 'Staatliches', 'Stardos Stencil', 'Syne', 'Tajawal', 'Teko',
  'Tinos', 'Titillium Web', 'Tomorrow', 'Trirong', 'Truculenta', 'Ubuntu', 'Ubuntu Condensed',
  'Ubuntu Mono', 'Unbounded', 'Unna', 'Urbanist', 'Varela Round', 'Vollkorn', 'Wix Madefor Display',
  'Wix Madefor Text', 'Work Sans', 'Yanone Kaffeesatz', 'Yantramanav', 'Yeseva One', 'Zilla Slab',
];
